dependency-dir: ./src/

depends:
    - crc
    - serial-datagram:
        fork: Stapelzeiger
    - parameter:
        fork: Stapelzeiger
    - simplerpc
    - pid
    - arm-cortex-tools
    - timestamp
    - msgbus

target.arm:
    - src/main.c
    - src/panic_log.c
    - src/sntp/sntp.c
    - src/commands.c
    - src/board/board.c
    - src/rpc_server.c
    - src/rpc_callbacks.c
    - src/msg_callbacks.c
    - src/uavcan_node.cpp
    - src/blocking_uart_driver.c
    - src/config.c
    - src/interface_panel.c
    - src/motor_driver.c
    - src/motor_driver_uavcan.cpp
    - src/motor_manager.c
    - src/stream.c
    - src/node_tracker.c
    - src/malloc_lock.c
    - src/log.c
    - src/imu.c
    - src/usbconf.c
    - src/base/encoder.c
    - src/base/position_manager.c

source:
    - src/unix_timestamp.c
    - src/bus_enumerator.c
    - src/trajectories.c
    - src/base/polar.c
    - src/base/odometry.c
    - src/base/base_controller.c

include_directories:
    - src/
    - src/board/

tests:
    - tests/ch.cpp
    - tests/log.c
    - tests/unix-timestamp.cpp
    - tests/bus_enumerator.cpp
    - tests/polar_test.cpp
    - tests/odometry_test.cpp
    - tests/base_controller_test.cpp

templates:
    app_src.mk.jinja: app_src.mk
    CMakeLists.txt.jinja: CMakeLists.txt
